name: Build and Publish

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          create_prerelease: ${{ github.ref == 'refs/heads/master' }}
          prerelease_name: "latest"
