name: Pull Request Check

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and verify
        uses: ./.github/actions/build
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          create_prerelease: false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterdog
          path: target/Waterdog.jar