name: Release Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version to release
        run: |
          sed -i -e s/#build/"release"/g ./src/main/java/dev/waterdog/waterdogpe/VersionInfo.java

      - name: Build
        uses: ./.github/actions/build
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          create_prerelease: false # Use custom release step

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            target/Waterdog.jar
          draft: false
          prerelease: false